<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ProzorroMining.Api</RootNamespace>
    <AssemblyName>ProzorroMining.Api</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProzorroMining.App\ProzorroMining.App.csproj" />
    <ProjectReference Include="..\ProzorroMining.Contracts\ProzorroMining.Contracts.csproj" />
  </ItemGroup>

</Project>
